Hyperlink text color for mobile changed.
Cambuzz/core pull request #8
Opened 2016-09-29 14:31 UTC by mashrin

2016-09-29 15:59 UTC, prastut requested changes

2016-09-29 15:59 UTC, prastut commented on index.php
> +                        <a class="page-scroll" href="aboutus/index.php" style="color: rgb(224,255,255)">About</a>
* Don't write inline styles. Merge them with css. 
* Don't use `rgb`. Use `hex` based colors. 
* This makes changes at all screen sizes (Even at desktop too). I need these changes only at mobile.

2016-09-29 15:59 UTC, prastut commented on index.php
> +?>
Have a whitespace at the end of the file. Don't remove.

2016-09-29 15:59 UTC, prastut commented on aboutus/index.php
> +                                <input name="name" type="text" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="       Name" id="name" />
* This is a hackish way to go about it. 
* We care about code as much as we care about design. 
* Use CSS to your aid.

2016-10-12 13:16 UTC, mashrin commented on index.php
> +                        <a class="page-scroll" href="aboutus/index.php" style="color: rgb(224,255,255)">About</a>
@prastut will correct it soon.

And on desktop the color anyway was the same. Isn't it?

2016-10-12 14:04 UTC, closed without merging